# Generated by Django 4.1.2 on 2022-10-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('DV', 'Developer'), ('JD', 'Junior Developer'), ('TL', 'Team Lead'), ('MG', 'Manager')], max_length=50)),
                ('salary', models.FloatField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='InsuaranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=50)),
                ('policy_number', models.CharField(max_length=50)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.employeedetails')),
            ],
        ),
    ]
