# Generated by Django 4.1.2 on 2022-10-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedetails',
            options={'verbose_name_plural': 'Employee Details'},
        ),
        migrations.AlterModelOptions(
            name='insuarancedetails',
            options={'verbose_name_plural': 'Insurance Details'},
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
