# Generated by Django 4.1.3 on 2022-11-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
